hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "2697e02e79ba657a756f819351d5f154d134c149d9669bdb056e57cd523785e6"

[[files]]
file = "config/dynamic_fps.json"
hash = "06430a1a5a3bd0b62648078deb022a4ec315f115f790755a06e4093ca00a56ec"

[[files]]
file = "config/entityculling.json"
hash = "6e961d971f43e378643ce2a6101bc8899c63c77c661098bf6af3555b5b1dec57"

[[files]]
file = "config/iris.properties"
hash = "2d5674bc7afd230d7a32757a6e627f070edf6c58ab3ba221b864840ece8b503d"

[[files]]
file = "config/shulkerboxtooltip.json5"
hash = "42bdf9884f0f85ed925e118b250cf9e66d2324f3e83ce103f3f1236c82d00533"

[[files]]
file = "config/simplehudenhanced.toml"
hash = "4100576c744caa473e9f46b2db38736efa9bbb57a2d7c9b6931f100bc914e7df"

[[files]]
file = "config/zoomify.json"
hash = "60a78fe1b271ce9b53e295235eb5a7cdb3a8692ca583fdaa7f5bc09f9049e2f4"

[[files]]
file = "icon.png"
hash = "24f6f6d262fe028ec4b3931ac4e720848d0e725afb00f8d64841c4df3cdc09c8"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "904365e7891802e522e5a35189b7039e18f56a22ab30bd99af59b97ec4b7468e"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "a8785544fb032c24853b8ed9bb15d65c30312f1ee5f7ada3e73a0350512702a0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "72f3dbfcfbf16d8437d865b090c4338cf32de86f290e8e8dde5626cb301bb4c7"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6adf5f512651c200a320219c32a3a51c8b95e219206f64b99cb93940d51b2cfa"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "09d9bcf41357ee2baf28a26418bc1ed5d68ad7044252e976081295bde8dddb2e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cf6edd71a012b437bca4bcac93c44d1109632db31b5f638d28b58fa77cf771b5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "dc930299b4c11cbd31712a3b91231bac4be1f34d00a464bfbe1a0674f5187d11"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "442468b81b595bb843af8ca225b51dbf5389f3ddaf07c009d1d2e6bc9f8d7610"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "88a36b21d538d44aca7dd0a7e5ad8c09b1b263be3f4381e3bb22bc9f94ee7290"
metafile = true

[[files]]
file = "mods/ly-clumps.pw.toml"
hash = "3f4c625156d62786a0c2803c8bd07f12ed1bd292949460104970bbe8df9a35a7"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "43b7544c0a49c9368caf33a1529a720c6fadb17f7d07db6a8e952b514b5a862c"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6dbca2c20d66b076bb4e8959ea0e26887991acf48f785aae402e066d5e3eb6ea"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "05e66fdfaf3f922718f38a18090c498d612160d342a7e3846fb7f666cf8bac3d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "8eb360a7056cd39f75c60123c9f4069dd607c67862fe22d1d83397f87d4e485a"
metafile = true

[[files]]
file = "mods/retino.pw.toml"
hash = "512c2bd9b6cd2a1e25c362734d5b7cdb98663daed6efd0075bff9d523471b70b"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "74be0b1016b6ed8a42c1b819af90393c2c74ac7e43248508d03ab7d7b6d55a07"
metafile = true

[[files]]
file = "mods/simple-hud-enhanced.pw.toml"
hash = "27e5f5b43aa1f108b31f19b15c2bc708044eb23b28f2a7ba4726b014243a9ea3"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "4d801184db14d95a0084083f61c6331e2c1090203b5639809ea1471effc9417d"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "382ad4f938be83c05d9ae6dc7bf24581f54173f5345c485abf3e3ff7618bb59e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f61bd9fbfa3fcc5d8267b5cbe6af08c93385752ddc6e6b74df0fbcfd5747e413"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "1dcded58f392b753b3acaaae02573c5d52e16672eab0e7cab66fc5f21eec6b5e"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d74d244b3524bea2326becd2ceaa27b8e231156aba33448533cd29b12ed48318"
metafile = true

[[files]]
file = "options.txt"
hash = "c7e40208bdfadba280dc2f14a94c3721e67b37dca8cc5ca17b9483944f59eb07"

[[files]]
file = "resourcepacks/highlighted-ores-texturepack.pw.toml"
hash = "cbb6a5ba45b70ee9b2060ec7f41ddec7f5d37f11b1838e381dc359be5cba86b5"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "5c88e075533df7079b0ef77684f2a71bb8743722a755f24978b2a9a1405c4bd6"
metafile = true

[[files]]
file = "shaderpacks/BSL_v8.4.01.1.zip.txt"
hash = "7b058f9c5daf7dda4edaf24d2755c5462e17bc64beb221d895a572da24e701e4"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.3.zip.txt"
hash = "db3007e30cb67eee638e262505eed982f9ac28dceae31ba3d183b551f2fafc24"

[[files]]
file = "shaderpacks/ComplementaryUnbound_r5.3.zip.txt"
hash = "dcb1f267a0a228ed75b11f0911c558ce32205431161bec449c7e73ca1de2216b"

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "d30923bf5cfb4988a372508cb461d8077609d79a38d0b170785804c7ad15f16e"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true

[[files]]
file = "shaderpacks/makeup-ultra-fast-shaders.pw.toml"
hash = "05dd4aac0131eeef4c1ff5601c294e615cbc38890e50dda7ecbd18c14d2748eb"
metafile = true

[[files]]
file = "shaderpacks/mellow.pw.toml"
hash = "55191ceeb84776cf184dbce17983b966ab9a16b166c95664cb01fa161b980ccb"
metafile = true

[[files]]
file = "shaderpacks/miniature-shader.pw.toml"
hash = "8ce5793226da3a42adaf0b6de42a917e47d9da31d6227fd53a06033dbbe47911"
metafile = true
