name = "Mac OS Optimized"
author = "scriptmunkee"
version = "1.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa9c4bfcabd1762d5499bc73c60049324207df3c8e33b3ded5a852b2aba9bbb8"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.9"]
