name = "Mac OS Optimized"
author = "scriptmunkee"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7990b62e5f1e124a613801657696b5e6278c1eccda67e1ce40a0f3fc652f3b0b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.8", "1.27.7"]
