name = "Mac OS Optimized"
author = "scriptmunkee"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "036f57aaf9c718bb7710ad5ba43591800ae539aaf774ae3b2d03ca686c6eb49f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.6"

[options]
acceptable-game-versions = ["1.21.6", "1.21.5"]
